# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
####
  # Frontend
  nextjs:
    build:
      context: ./front-end/ecodash/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - secodash-network
        
####
  # nginx proxy server
  nginx:
    build:
      context: ./front-end/nginx/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    secrets:
     - ssl-certificate
     - ssl-private-key
    networks:
      - secodash-network

#####
  # Spider
  spider-app:
    build:
      context: ./spider/
      dockerfile: ./Dockerfile
    networks:
      - secodash-network
    secrets:
      - git-api-token
    environment:
      API_Token_File: /run/secrets/git-api-token
      ASPNETCORE_URLS: http://*:5205
      Docker_Enviroment: local
    ports:
      - 5205:5205

#####
  # SQL Database 
  db:
    image: postgres
    networks:
      - secodash-network
    secrets:
      - db-password
    environment:
      POSTGRES_Username: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
####
  # Database browser
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - secodash-network
    restart: always
####
  # Backend (service) layer application
  backend-app:
    build:
      context: ./back-end/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:5003
      Docker_Enviroment: local
    ports:
      - 5003:5003
    networks:
      - secodash-network
    restart: always
    depends_on:
      - db
    
####
  # Volumes, networks and secrets
volumes:
  postgres-data:

secrets:
  db-password:
    file: secrets/db-password.txt
  git-api-token:
    file: secrets/spider-git-api-token.txt
  ssl-certificate:
    file: secrets/certs/fullchain.pem
  ssl-private-key:
    file: secrets/certs/privkey.pem
    

networks:
  secodash-network:
    name: secodash-network
    driver: bridge
    external: true