# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
####
  # Frontend
  nextjs:
    build:
      context: ./front-end/ecodash/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:3000
    ports:
      - 3000:3000
    networks:
      - secodash-network
    restart: always
    
  nginx:
    build:
      context: ./front-end/nginx/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./front-end/nginx/certs:/certs:ro #certs on local
    networks:
      - secodash-network
#####
  # Spider
  spider-app:
    build:
      context: ./spider/
      dockerfile: ./Dockerfile
    networks:
      - secodash-network
    environment:
      API_Token: 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
      ASPNETCORE_URLS: http://*:5205
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: ./certs/privkey.pem
      ASPNETCORE_Kestrel__Certificates__Default__Path: ./certs/fullchain.pem
    ports:
      - 5205:5205
    volumes:
      - ./front-end/nginx/certs:/publish/certs:ro

#####
  # Backend 
  db:
    image: postgres
    networks:
      - secodash-network
    restart: always
    environment:
      POSTGRES_Username: postgres
      POSTGRES_PASSWORD: SECODash
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - secodash-network
    restart: always
  backend-app:
    build:
      context: ./back-end/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:5003
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: ./certs/privkey.pem
      ASPNETCORE_Kestrel__Certificates__Default__Path: ./certs/fullchain.pem
    ports:
      - 5003:5003
    networks:
      - secodash-network
    restart: always
    depends_on:
      - db
    volumes:
      - ./front-end/nginx/certs:/publish/certs:ro
    
####
  # Volumes and networks 
volumes:
  postgres-data:

networks:
  secodash-network:
    name: secodash-network
    driver: bridge
    external: true