# 
# This is the compose file used for development purposes. For more information read the documentation
# 
services:
  # Frontend docker.
  server:
    build:
      context: ./front-end/ecodash/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:3000
    ports:
      - 3000:3000
    networks:
      - secodash-network
    restart: always
    
#####
  # Spider docker.
  spider-app:
    container_name: spider-app
    build:
      context: ./spider/
      dockerfile: ./Dockerfile
    networks:
      - secodash-network
    environment:
      API_Token: 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
      ASPNETCORE_URLS: http://+:5205
    ports:
      - 5205:5205

#####
  # Backend docker.
  db:
    container_name: db
    image: postgres
    networks:
      - secodash-network
    restart: always
    build:
      context: ./database
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_Username: postgres
      POSTGRES_PASSWORD: SECODash
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - secodash-network
    restart: always
    
  backend-app:
    container_name: backend-app
    build:
      context: ./back-end/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5003
    ports:
      - 5003:5003
    networks:
      - secodash-network
    restart: always
    depends_on:
      - db
    
  #####
  # Data processor docker.
  data-processor-app:
    container_name: data-processor-app
    build:
      context: ./data_processor/
      dockerfile: ./Dockerfile
    networks:
      - secodash-network
    ports:
      - 5000:5000
    
volumes:
  postgres-data:

networks:
  secodash-network:
    name: secodash-network
    driver: bridge
    external: true