#
# This file is used to compose the project on the server
# It has some server specific server-side only specifications
#
services:
####
  # Frontend
  nextjs:
    build:
      context: ./front-end/ecodash/
      dockerfile: ./Dockerfile
    networks:
      - secodash-network
    restart: always
    
####
  # nginx proxy server
  nginx:
    build:
      context: ./front-end/nginx/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    secrets:
     - ssl-certificate
     - ssl-private-key
    networks:
      - secodash-network
    restart: always
    
#####
  # Spider
  spider-app:
    container_name: spider-app
    build:
      context: ./spider/
      dockerfile: ./Dockerfile
    networks:
      - secodash-network
    secrets:
      - git-api-token
    environment:
      API_Token_File: /run/secrets/git-api-token
      ASPNETCORE_URLS: http://*:5205
      Docker_Enviroment: server

#####
  # Backend 
  db:
    container_name: db
    image: postgres
    networks:
      - secodash-network
    secrets:
      - db-password
    restart: always
    build:
      context: ./database
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_Username: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
 ####
  # Backend (service) layer application
  backend-app:
    container_name: backend-app
    build:
      context: ./back-end/
      dockerfile: ./Dockerfile
    secrets:
      - backend-secrets
    environment:
      backend-secrets: /run/secrets/backend-secrets
      ASPNETCORE_URLS: http://*:5003
      Docker_Enviroment: server
    networks:
      - secodash-network
    restart: always
    depends_on:
      - db
    
#####
  # Data processor docker.
  data-processor-app:
    container_name: data-processor-app
    build:
      context: ./data_processor/
      dockerfile: ./Dockerfile
    networks:
      - secodash-network
    restart: always
      
####
  # Volumes, networks and secrets
volumes:
  postgres-data:

secrets:
  backend-secrets:
    file: secrets/backend-connectionstrings.json
  db-password:
    file: secrets/db-password.txt
  git-api-token:
    file: secrets/spider-git-api-token.txt
  ssl-certificate:
    file: secrets/certs/fullchain.pem
  ssl-private-key:
    file: secrets/certs/privkey.pem

networks:
  secodash-network:
    name: secodash-network
    driver: bridge
    external: true