#
# This file should be identical to the docker-compose file aside from the certificates
#
services:
####
  # Frontend
  nextjs:
    build:
      context: ./front-end/ecodash/
      dockerfile: ./Dockerfile
    networks:
      - secodash-network
    restart: always
    
####
  # nginx proxy server
  nginx:
    build:
      context: ./front-end/nginx/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /local/certs:/certs:ro #certs on server
    networks:
      - secodash-network
    restart: always
    
#####
  # Spider
  spider-app:
    build:
      context: ./spider/
      dockerfile: ./Dockerfile
    networks:
      - secodash-network
    environment:
      API_Token: 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
      ASPNETCORE_URLS: http://*:5205
      Docker_Enviroment: server
    volumes:
      - /local/certs:/publish/certs:ro

#####
  # Backend 
  db:
    image: postgres
    networks:
      - secodash-network
    restart: always
    environment:
      POSTGRES_Username: postgres
      POSTGRES_PASSWORD: SECODash
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  backend-app:
    build:
      context: ./back-end/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:5003
      Docker_Enviroment: server
    networks:
      - secodash-network
    restart: always
    depends_on:
      - db
    volumes:
      - /local/certs:/publish/certs:ro
      
####
  # Volumes and networks 
volumes:
  postgres-data:

networks:
  secodash-network:
    name: secodash-network
    driver: bridge
    external: true