#
# This file should be identical to the docker-compose file aside from the certificates
#
services:
####
  # Frontend
  nextjs:
    build:
      context: ./front-end/ecodash/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:3000
    ports:
      - 3000:3000
    networks:
      - secodash-network
    restart: always
  nginx:
    build:
      context: ./front-end/nginx/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /local/certs:/certs:ro #certs on server
    networks:
      - secodash-network
#####
  # Spider
  spider-app:
    build:
      context: ./spider/
      dockerfile: ./Dockerfile
    networks:
      - secodash-network
    environment:
      API_Token: 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
      ASPNETCORE_URLS: http://+:5205
    ports:
      - 5205:5205

#####
  # Backend 
  db:
    image: postgres
    networks:
      - secodash-network
    restart: always
    environment:
      POSTGRES_Username: postgres
      POSTGRES_PASSWORD: SECODash
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - secodash-network
    restart: always
  backend-app:
    build:
      context: ./back-end/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5003
    ports:
      - 5003:5003
    networks:
      - secodash-network
    restart: always
    depends_on:
      - db
    
####
  # Volumes and networks 
volumes:
  postgres-data:

networks:
  secodash-network:
    name: secodash-network
    driver: bridge
    external: true